name: Test

on:
  push:
    branches:
      - '**'

jobs:

  test:
    strategy:
      matrix:
        go: [1.17.x, 1.18.x, 1.19.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
        GOFLAGS: -mod=readonly

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: go test -race -parallel 1 -short ./internal/...

    - name: Build
      run: go build -race ./cmd/server/main.go